vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

require("user.lazy")
require("user.plugins")
require('user.lspcolors')
require("user.impatient")
require("user.options")
require("user.keymaps")
require("user.autocommands")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require('user.lsp')
require('user.cmp')
require("user.lualine")
require("user.illuminate")
require("user.indentline")
require("user.trouble")
require("user.noice")
require("user.project")
